/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
/* eslint-disable */
import { App } from "./index"

// @ts-ignore
export function indexTemplateHtml(this: App) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',[_c('div',{staticStyle:{"margin-left":"210px","margin-top":"10px"}},[_c('div',{style:(_vm.canvasStyle)},[_c('div',{style:(_vm.styleGuideStyle)},_vm._l((_vm.renderResults),function(r){return _c('div',[_c('div',{style:({ left: r.x + 'px', top: r.y + 'px', position: 'absolute' })},[_c('div',{domProps:{"innerHTML":_vm._s(r.html)}})])])}),0)]),_vm._v(" "),_c('div',{style:(_vm.maskStyle),on:{"wheel":_vm.canvasWheel,"mousedown":_vm.canvasMousedown,"mouseup":_vm.canvasMouseup}})]),_vm._v(" "),(_vm.selection.kind === 'content')?_c('div',[(_vm.selection.content.kind === 'text')?_c('div',[_c('input',{attrs:{"type":"text"},domProps:{"value":_vm.selection.content.text},on:{"change":_vm.changeText}})]):_vm._e(),_vm._v(" "),(_vm.selection.content.kind === 'image')?_c('div',[_c('input',{attrs:{"type":"text"},domProps:{"value":_vm.selection.content.url},on:{"change":_vm.changeImageUrl}})]):_vm._e()]):_vm._e(),_vm._v(" "),_c('button',{on:{"click":function($event){return _vm.applyChanges()}}},[_vm._v("apply changes")]),_vm._v(" "),_c('input',{directives:[{name:"model",rawName:"v-model",value:(_vm.auto),expression:"auto"}],attrs:{"type":"checkbox"},domProps:{"checked":Array.isArray(_vm.auto)?_vm._i(_vm.auto,null)>-1:(_vm.auto)},on:{"change":function($event){var $$a=_vm.auto,$$el=$event.target,$$c=$$el.checked?(true):(false);if(Array.isArray($$a)){var $$v=null,$$i=_vm._i($$a,$$v);if($$el.checked){$$i<0&&(_vm.auto=$$a.concat([$$v]))}else{$$i>-1&&(_vm.auto=$$a.slice(0,$$i).concat($$a.slice($$i+1)))}}else{_vm.auto=$$c}}}}),_vm._v("\n  auto\n")])}
// @ts-ignore
export var indexTemplateHtmlStatic = [  ]
/* eslint-enable */
// tslint:enable
