/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
/* eslint-disable */
import { CanvasMask } from "./canvas-mask"
import { DraggingArea } from "./dragging-area"
import { EditorPanel } from "./editor-panel"
import { App } from "./index"

// @ts-ignore
export function canvasMaskTemplateHtml(this: CanvasMask) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{style:(_vm.maskStyle),on:{"wheel":_vm.canvasWheel,"mousedown":_vm.canvasMousedown,"mouseup":_vm.canvasMouseup,"mousemove":_vm.canvasMousemove}})}
// @ts-ignore
export var canvasMaskTemplateHtmlStatic = [  ]
// @ts-ignore
export function draggingAreaTemplateHtml(this: DraggingArea) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return (_vm.canvasState.mousePressing && _vm.canvasState.isDragging)?_c('div',{style:(_vm.draggingAreaStyle)}):_vm._e()}
// @ts-ignore
export var draggingAreaTemplateHtmlStatic = [  ]
// @ts-ignore
export function editorPanelTemplateHtml(this: EditorPanel) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',[(_vm.canvasState.selection.kind === 'content')?_c('div',[(_vm.canvasState.selection.content.kind === 'text')?_c('div',[_c('input',{attrs:{"type":"text"},domProps:{"value":_vm.canvasState.selection.content.text},on:{"change":_vm.changeText}})]):_vm._e(),_vm._v(" "),(_vm.canvasState.selection.content.kind === 'image')?_c('div',[_c('input',{attrs:{"type":"text"},domProps:{"value":_vm.canvasState.selection.content.url},on:{"change":_vm.changeImageUrl}})]):_vm._e()]):_vm._e(),_vm._v(" "),_c('button',{on:{"click":function($event){return _vm.canvasState.applyChanges()}}},[_vm._v("apply changes")]),_vm._v(" "),_c('input',{directives:[{name:"model",rawName:"v-model",value:(_vm.canvasState.auto),expression:"canvasState.auto"}],attrs:{"type":"checkbox"},domProps:{"checked":Array.isArray(_vm.canvasState.auto)?_vm._i(_vm.canvasState.auto,null)>-1:(_vm.canvasState.auto)},on:{"change":function($event){var $$a=_vm.canvasState.auto,$$el=$event.target,$$c=$$el.checked?(true):(false);if(Array.isArray($$a)){var $$v=null,$$i=_vm._i($$a,$$v);if($$el.checked){$$i<0&&(_vm.$set(_vm.canvasState, "auto", $$a.concat([$$v])))}else{$$i>-1&&(_vm.$set(_vm.canvasState, "auto", $$a.slice(0,$$i).concat($$a.slice($$i+1))))}}else{_vm.$set(_vm.canvasState, "auto", $$c)}}}}),_vm._v("\n  auto\n")])}
// @ts-ignore
export var editorPanelTemplateHtmlStatic = [  ]
// @ts-ignore
export function indexTemplateHtml(this: App) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',[_c('div',{staticStyle:{"margin-left":"210px","margin-top":"10px","position":"absolute"}},[_c('div',{style:(_vm.canvasStyle)},[_c('div',{style:(_vm.styleGuideStyle)},_vm._l((_vm.canvasState.renderResults),function(r){return _c('div',[_c('div',{style:({ left: r.x + 'px', top: r.y + 'px', position: 'absolute' })},[_c('div',{domProps:{"innerHTML":_vm._s(r.html)}})])])}),0)]),_vm._v(" "),_c('dragging-area',{attrs:{"canvasState":_vm.canvasState}}),_vm._v(" "),_c('canvas-mask',{attrs:{"canvasState":_vm.canvasState}})],1),_vm._v(" "),_c('editor-panel',{attrs:{"canvasState":_vm.canvasState}})],1)}
// @ts-ignore
export var indexTemplateHtmlStatic = [  ]
/* eslint-enable */
// tslint:enable
